---
- name: >-
    Ensure hardware facts are gathered for all devices to perform the version
    checks
  cisco.ios.ios_facts:
    gather_subset:
      - hardware

- name: Assert that device version is greater than minimum version
  ansible.builtin.assert:
    that:
      - ansible_net_version > minimum_ios_version
    fail_msg: >-
      Current version {{ ansible_net_version }} is lower than minimum
      requirement, version {{ minimum_ios_version }}. Please update device
      firmware to version {{ minimum_ios_version }} or greater.
    success_msg: >-
      Current version {{ ansible_net_version }} meets minimum version
      requirements.

- name: >-
    Obtain information from the app-hosting archive provided to ensure it is
    correct for the device
  block:
    - name: >-
        Ensure a temporary directory exists to extract the app-hosting archive
        into
      ansible.builtin.tempfile:
        state: directory
        suffix: app-hosting-archive
      delegate_to: localhost
      notify:
        - Remove app-hosting archive extraction tmpdir
      register: _app_hosting_archive_tmpdir

    - name: Extract the app-hosting archive to the tmpdir
      ansible.builtin.unarchive:
        dest: "{{ _app_hosting_archive_tmpdir.path }}"
        src: "{{ cybervision_sensor_cli_app_archive }}"
      delegate_to: localhost
  rescue:
    - name: Force temporary directory removal by flushing handlers
      ansible.builtin.meta: flush_handlers

    - name: Fail out after deleting temporary files
      ansible.builtin.fail:
        msg: Failed to extract the app-hosting archive to the tmpdir

- name: Load package.yaml into facts
  ansible.builtin.set_fact:
    _package: >-
      {{
        (lookup("ansible.builtin.file", _app_hosting_archive_tmpdir.path +
        "/package.yaml") | ansible.builtin.from_yaml)
      }}

- name: Check app type (IC3K)
  ansible.builtin.assert:
    that:
      - _package.app.cpuarch == "x86_64"
      - _package.app.type == "vm"
  when:
    - "'IC3000' in group_names"

- name: Check app type (CAT9K)
  ansible.builtin.assert:
    that:
      - _package.app.cpuarch == "x86_64"
      - _package.app.type == "docker"
  when: >-
    'C9XXX' in group_names or
    'IR8340' in group_names

- name: Check app type (IR1XXX, IE3X00 and IE9300)
  ansible.builtin.assert:
    that:
      - _package.app.cpuarch == "aarch64"
      - _package.app.type == "docker"
  when: >-
    'IR1XXX' in group_names or
    'IE3X00' in group_names or
    'IE9300' in group_names

- name: Verify Cyber Vision Center version
  block:
    - name: Get center version
      connection: local
      ansible.builtin.uri:
        validate_certs: false
        url: "{{ cybervision_sensor_cli_center_url | mandatory }}/api/3.0/version"
        method: GET
        headers:
          x-token-id: "{{ cybervision_sensor_cli_center_token | mandatory }}"
        body_format: json
      register: center_version_result

    - name: Register center version
      ansible.builtin.set_fact:
        center_version_json: "{{ center_version_result.json }}"
      connection: local

    - name: Register center version
      ansible.builtin.set_fact:
        center_version: "{{ center_version_json.major }}.{{ center_version_json.minor }}.{{ center_version_json.incr }}"
      connection: local

    - name: Check center version
      ansible.builtin.assert:
        that:
          - center_version is version('3.2.1', '>=')
        fail_msg: "Current Cyber Vision Center (CVC) version {{ center_version }} is lower than minimum requirement, please update CVC"
        success_msg: "Current Cyber Vision Center version {{ center_version }} meets minimum version requirements"

- name: Verify Cyber Vision Sensor version
  block:
    - name: Register sensor version
      ansible.builtin.set_fact:
        sensor_version: "{{ _package.info.version.split('+')[0] }}"
      connection: local

    - name: Check sensor version
      ansible.builtin.assert:
        that:
          - sensor_version is version(center_version, '=')
      when:
        - check_sensor_and_center_version

- name: Extract host serial number
  block:
    - name: Show inventory
      cisco.ios.ios_command:
        commands: 'show inventory'
      register: inventory

    - name: Extract the serial number of the device
      ansible.builtin.set_fact:
        serial_number: "{{ inventory.stdout | regex_findall('SN:\\s+(\\w+)') | default('Not found') }}"

    - name: Register serial number of the device
      ansible.builtin.set_fact:
        serial: "{{ serial_number[0] }}"
      connection: local

- name: Set sensor ID
  block:
    - name: Check if sensor exists
      connection: local
      ansible.builtin.uri:
        validate_certs: false
        url: "{{ cybervision_sensor_cli_center_url | mandatory }}/api/3.0/sensors"
        method: GET
        headers:
          x-token-id: "{{ cybervision_sensor_cli_center_token | mandatory }}"
        body_format: json
      register: sensor_list

    - name: Get sensor id
      ansible.builtin.set_fact:
        sensor_id: "{{ sensor_list.json | json_query(jmesquery) }}"
      connection: local
      vars:
        jmesquery: "[? serialNumber==`{{ serial }}`].id"

    - name: Default value for sensor id
      ansible.builtin.set_fact:
        sensor_id: "{{ sensor_id[0] if sensor_id != [] else '' }}"
      connection: local

- name: Copy installation file to the host
  block:
    - name: Get the application tar file name
      ansible.builtin.set_fact:
        application_file: "{{ cybervision_sensor_cli_app_archive | regex_findall('.*/(.*.tar)$') | default('Not found') }}"

    - name: Select storage
      ansible.builtin.set_fact:
        storage: "{{ 'flash:' if 'IE3X00' in group_names else 'bootflash:' if 'C9XXX' or 'IE9300' or 'IR1XXX' or 'IR8340' in group_names }}"
      connection: local

    - name: Copy the application tar file to the device
      cisco.ios.ios_command:
        commands:
          - command: "copy scp://{{ cv_scp_username }}:{{ cv_scp_password | urlencode }}@{{ cybervision_sensor_cli_ansible_controller }}/{{ cybervision_sensor_cli_app_archive }} {{ storage }}"
            prompt: 'Destination filename \[{{ application_file[0] }}\]?'
            answer: "\r"
      vars:
        ansible_command_timeout: 360

- name: Install the app
  ansible.builtin.import_tasks: install.yml
  when: mode == 'install'

- name: Update the app
  ansible.builtin.import_tasks: update.yml
  when: mode == 'update'

- name: Activate the app
  ansible.builtin.import_tasks: activate.yml
  when: mode == 'install'

- name: Start the app
  ansible.builtin.import_tasks: start.yml
  when: mode == 'install'

- name: Show app-hosting list
  cisco.ios.ios_command:
    commands: 'show app-hosting list'
  register: app_hosting_list

- name: Print App hosting list
  ansible.builtin.debug:
    msg: "{{ app_hosting_list.stdout_lines }}"

- name: Get the app name for update
  ansible.builtin.set_fact:
    app_list: "{{ app_hosting_list.stdout_lines | regex_findall('(\\w+)\\s+(\\w+)', multiline=True) | default('No match found') }}"

- name: Print the app name
  ansible.builtin.debug:
    msg: "The app name is {{ app_list }}"

- name: Get app status
  ansible.builtin.set_fact:
    app_status: "{{ app_list[1][1] }}"
  connection: local

- name: Check if sensor exists
  connection: local
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ cybervision_sensor_cli_center_url | mandatory }}/api/3.0/sensors"
    method: GET
    headers:
      x-token-id: "{{ cybervision_sensor_cli_center_token | mandatory }}"
    body_format: json
  register: sensor_list

- name: Get sensor id
  ansible.builtin.set_fact:
    sensor_id: "{{ sensor_list.json | json_query(jmesquery) }}"
  connection: local
  vars:
    jmesquery: "[? serialNumber==`{{ serial }}`].id"

- name: Default value for sensor id
  ansible.builtin.set_fact:
    sensor_id: "{{ sensor_id[0] if sensor_id != [] else '' }}"
  connection: local

- name: Check sensor status
  connection: local
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ cybervision_sensor_cli_center_url | mandatory }}/api/3.0/sensors"
    method: GET
    headers:
      x-token-id: "{{ cybervision_sensor_cli_center_token | mandatory }}"
    body_format: json
  register: sensor_list

- name: Get enrollment status
  ansible.builtin.set_fact:
    enrollment_status: "{{ sensor_list.json | json_query(jmesquery) }}"
  connection: local
  vars:
    jmesquery: "[? serialNumber==`{{ serial }}`].status.enrollmentStatus"

- name: Enroll
  ansible.builtin.import_tasks: enroll.yml

- name: Pause for 3 minutes to wait for app restart & center connectivity
  ansible.builtin.pause:
    minutes: 3
  when: check_sensor_status is defined and check_sensor_status

- name: Check sensor status
  connection: local
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ cybervision_sensor_cli_center_url | mandatory }}/api/3.0/sensors"
    method: GET
    headers:
      x-token-id: "{{ center_token | mandatory }}"
    body_format: json
  register: sensor_list
  when: check_sensor_status is defined and check_sensor_status

- name: Get sensor status
  ansible.builtin.set_fact:
    sensor_status: "{{ sensor_list.json | json_query(jmesquery) }}"
  connection: local
  vars:
    jmesquery: "[? serialNumber==`{{ serial }}`].status.operationalStatus"
  when:
    - check_sensor_status is defined

- name: Check sensor is connected
  ansible.builtin.assert:
    that:
      - sensor_status[0] == 'CONNECTED'
  when: check_sensor_status is defined and check_sensor_status
