---
- name: Remove provisioning temporary directory
  connection: local
  ansible.builtin.file:
    path: "{{ sensor_provisioning_temp_dir.path }}"
    state: absent

- name: Remove app-hosting archive extraction tmpdir
  connection: local
  ansible.builtin.file:
    path: "{{ _app_hosting_archive_tmpdir.path }}"
    state: absent
